dictionaries = ["en_us"]
words = [
  "autocomplete",
  "autocompletion",
  "auxclick",
  "bunx",
  "cdylib",
  "codemirror",
  "comemo",
  "comlink",
  "crawlable",
  "dedup",
  "dedupe",
  "debounce",
  "debounces",
  "debounced",
  "fontconfig",
  "fontdb",
  "frontmatter",
  "getrandom",
  "jspi",
  "krilla",
  "lezer",
  "libertinus",
  "memmap",
  "monorepo",
  "mousedown",
  "mousemove",
  "mouseup",
  "newtype",
  "noninteractive",
  "nums",
  "oklch",
  "oncompile",
  "onnavigate",
  "oxfmt",
  "oxlint",
  "pagebreak",
  "paged",
  "pointermove",
  "pointerup",
  "prerendered",
  "qcms",
  "recompiles",
  "reflows",
  "rlib",
  "rustc",
  "serializable",
  "shiki",
  "smallcaps",
  "solidjs",
  "tinymist",
  "tsify",
  "tsup",
  "tungsten",
  "typsten",
  "typst",
  "typst's",
  "typstogether",
  "typstyle",
  "vedivad",
  "vfs",
  "vite",
  "vite's",
  "vitest",
  "wasm",
  "xlink",
  "ydoc",
  "yjs",
]
include_paths = ["**/*.md", "**/*.ts"]
ignore_paths = ["**/dist/**", "packages/typsten/pkg/**", "**/*.d.ts"]
use_global = false
